services:
  api:
    build: .
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      WEATHER_API_KEY: M6UDSMETPNEPTEUZ4YUC69LNZ
      REDIS_URL: redis://redis:6379
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:8.6.3-alpine3.23
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge